##################################################################################################

stages:
    - test-sanitizers
    - test-release

##################################################################################################

test-sanitizers-focal:
    stage: test-sanitizers
    extends:
        - .setup_focal
        - .meson_test_sanitizers

test-release-focal:
    stage: test-release
    extends:
        - .setup_focal
        - .meson_test_release
    needs:
        - job: test-sanitizers-focal
          artifacts: false

##################################################################################################

# Sanitizers are apparently broken on bionic's version of clang
#test-sanitizers-bionic:
#    stage: test-sanitizers
#    extends:
#        - .setup_bionic
#        - .meson_test_sanitizers

# Commented out bionic test release due to missing std::filesystem on C++17 (should be included
# but is unfortunately not).
#test-release-bionic:
#    stage: test-release
#    extends:
#        - .setup_bionic
#        - .meson_test_release
#    needs:
#        - job: test-sanitizers-bionic
#          artifacts: false

##################################################################################################

test-sanitizers-buster:
    stage: test-sanitizers
    extends:
        - .setup_buster
        - .meson_test_sanitizers

test-release-buster:
    stage: test-release
    extends:
        - .setup_buster
        - .meson_test_release
    needs:
        - job: test-sanitizers-buster
          artifacts: false

##################################################################################################
# Now the templates ...
.meson_test_release:
    script:
        - echo "================================================================================"
        - echo "Build & test library in release mode ..."
        - ls /export/doocs/lib/pkgconfig
        - meson setup build.release
            --pkg-config-path=${CI_PROJECT_DIR}/lib/pkgconfig:/export/doocs/lib/pkgconfig
            --buildtype=release
            --prefix=/export/doocs
            --libdir=lib
            --includedir=lib/include
        - ninja -C build.release
        - cd build.release; ./taskolib_test
        - echo "... done."
    artifacts:
        paths:
            - build.release
        expire_in: 4 weeks

.meson_test_sanitizers:
    script:
        - echo "================================================================================"
        - echo "Build & test library in debug mode with ASAN & UBSAN ..."
        - ls /export/doocs/lib/pkgconfig
        - meson setup build.debug_asan_ubsan
            --pkg-config-path=${CI_PROJECT_DIR}/lib/pkgconfig:/export/doocs/lib/pkgconfig
            --buildtype=debug
            -Db_sanitize=address,undefined
        - ninja -C build.debug_asan_ubsan
        - cd build.debug_asan_ubsan; ./taskolib_test
        - echo "... done."
    artifacts:
        paths:
            - build.debug_asan_ubsan
        expire_in: 1 week

.setup_focal:
    image: ubuntu:20.04
    tags:
        - ubuntu20
    before_script:
        # Install build dependencies
        - echo "Install the basics (wget and gnupg) for setting up the docker focal image ..."
        - (export http_proxy="http://xfelproxy:3128/"; export https_proxy="http://xfelproxy:3128/";
            apt update && apt install -y wget gnupg)
        # Add DOOCS repo with key
        - echo "Installing MCS DOOCS package repository with key ..."
        - wget -O - http://doocs.desy.de/pub/doocs/DOOCS-key.gpg.asc | apt-key add -
        - echo "deb http://doocspkgs.desy.de/pub/doocs focal main" >> /etc/apt/sources.list.d/doocs-desy-intern.list
        - echo "deb-src http://doocspkgs.desy.de/pub/doocs focal main" >> /etc/apt/sources.list.d/doocs-desy-intern.list
        # Update APT cache
        - echo "Updating APT cache and installing basic libraries and header files for compiling DOOCS core libraries"
        - (export http_proxy="http://xfelproxy:3128/"; export https_proxy="http://xfelproxy:3128/"; apt update)
        # Install part of the packages required to compile and link DOOCS core libraries on a focal system
        - (export http_proxy="http://xfelproxy:3128/"; export https_proxy="http://xfelproxy:3128/";
            DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends git libldap2-dev libtirpc-dev
            build-essential binutils autotools-dev clang gcc-doc dh-exec dh-autoreconf cmake ninja-build meson pkg-config)
        # FIXME Just to make it work for now, use existing libs.
        - (export http_proxy="http://xfelproxy:3128/"; export https_proxy="http://xfelproxy:3128/";
            DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends dev-doocs-libgul14)
        - export DOOCSARCH=Ubuntu-20.04-x86_64

.setup_buster:
    image: debian:10.10
    tags:
        - debian10
    before_script:
        # Install build dependencies
        - echo "Install the basics (wget and gnupg) for setting up the docker buster image ..."
        - (export http_proxy="http://xfelproxy:3128/"; export https_proxy="http://xfelproxy:3128/";
            apt update && apt install -y wget gnupg)
        # Add DOOCS repo with key
        - echo "Installing MCS DOOCS package repository with key ..."
        - wget -O - http://doocs.desy.de/pub/doocs/DOOCS-key.gpg.asc | apt-key add -
        - echo "deb http://doocspkgs.desy.de/pub/doocs buster main" >> /etc/apt/sources.list.d/doocs-desy-intern.list
        - echo "deb-src http://doocspkgs.desy.de/pub/doocs buster main" >> /etc/apt/sources.list.d/doocs-desy-intern.list
        # Update APT cache
        - echo "Updating APT cache and installing basic libraries and header files for compiling DOOCS core libraries"
        - (export http_proxy="http://xfelproxy:3128/"; export https_proxy="http://xfelproxy:3128/"; apt update)
        # Install part of the packages required to compile and link DOOCS core libraries on a buster system
        - (export http_proxy="http://xfelproxy:3128/"; export https_proxy="http://xfelproxy:3128/";
            DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends git libldap2-dev libtirpc-dev
            build-essential binutils autotools-dev clang dh-exec dh-autoreconf cmake ninja-build meson pkg-config)
        # FIXME Just to make it work for now, use existing libs.
        - (export http_proxy="http://xfelproxy:3128/"; export https_proxy="http://xfelproxy:3128/";
            DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends dev-doocs-libgul14)
        - export DOOCSARCH=Debian-10-x86_64
