Taskolib: git::GitRepository Class Reference
git::GitRepository Class Reference
Detailed Description
A class to wrap used methods from C-Library libgit2.
This class is necessary to handle C-pointers in a way that C++ programmers using this class do not have to think about them.
This class does not reflect the full libgit2 library. git functions which are not implemented in this class will be implemented in case of necessity
#include <GitRepository.h>
Public Member Functions
GitRepository (const std::filesystem::path &file_path)
Constructor which specifies the root dir of the git repository.
void reset_repo ()
Reset all knowledge this object knows about the repository and load the knowledge again.
std::filesystem::path get_path () const
Returns member variable, which is the root dir of the git repository.
git_repository * get_repo ()
Returns a non-owning raw pointer to the current repository.
void add ()
Stage all new and changed files and folders in the repository directory.
std::vector< int > add_files (const std::vector< std::filesystem::path > &filepaths)
Stage specific files listed in filepaths.
std::string get_last_commit_message ()
Return the commit message of the HEAD commit.
void commit (const std::string &commit_message)
Commit staged changes to the master branch of the git repository.
void remove_directory (const std::filesystem::path &directory)
Deletes seq_repository and all files within.
std::vector< FileStatus > status ()
Returns current git status.
~GitRepository ()
Destructor.
Private Member Functions
void init (const std::filesystem::path &file_path)
Initialize a new git repository and commit all files in its path.
void commit_initial ()
Make the first commit.
LibGitPointer< git_commit > get_commit (int count)
Get a specific commit.
LibGitPointer< git_commit > get_commit (const std::string &ref)
Get a specific commit.
LibGitPointer< git_commit > get_commit ()
Get the HEAD commit.
void make_signature ()
Load a git signature or create a default signature.
std::vector< FileStatus > collect_status (LibGitPointer< git_status_list > &status) const
Translate all status information for each submodule into String.
void update ()
Update the tracked files in the repository.
Static Private Member Functions
static bool is_unstaged (FileStatus &filestats, const git_status_entry *s)
Check if the file from the status entry is not staged and collect the status in filestats.
static bool is_staged (FileStatus &filestats, const git_status_entry *s)
Check if the file from the status entry is not unstaged and collect the status in filestats.
Private Attributes
LibGitPointer< git_repository > repo_
Pointer which holds all infos of the active repository.
std::filesystem::path repo_path_
Path to the repository.
LibGitPointer< git_signature > my_signature_
Signature used in commits.
Constructor & Destructor Documentation
GitRepository()
git::GitRepository::GitRepository (const std::filesystem::path & file_path) explicit
Constructor which specifies the root dir of the git repository.
Parameters
file_path path to git directory
References init(), and repo_path_.
~GitRepository()
git::GitRepository::~GitRepository ()
Destructor.
References my_signature_, repo_, and git::LibGitPointer< T >::reset().
Member Function Documentation
add()
void git::GitRepository::add ()
Stage all new and changed files and folders in the repository directory.
References git::LibGitPointer< T >::get(), repo_, and git::repository_index().
add_files()
std::vector< int > git::GitRepository::add_files (const std::vector< std::filesystem::path > & filepaths)
Stage specific files listed in filepaths.
Parameters
filepaths list of files. Either relative to repository root or absolute.
Returns
list of indices. An index from the filepaths vector is returned if the staging of the file failed. Returns an empty vector if all files were staged successfully.
References git::LibGitPointer< T >::get(), repo_, and git::repository_index().
collect_status()
std::vector< FileStatus > git::GitRepository::collect_status (LibGitPointer< git_status_list > & status) const private
Translate all status information for each submodule into String.
Parameters
status C-type status of all submodules from libgit
Returns
A vector of dynamic length which contains a status struct
References git::FileStatus::changes, git::FileStatus::handling, is_staged(), is_unstaged(), git::FileStatus::path_name, and status().
Referenced by status().
commit()
void git::GitRepository::commit (const std::string & commit_message)
Commit staged changes to the master branch of the git repository.
Parameters
commit_message customized message for the commit
References git::LibGitPointer< T >::get(), get_commit(), my_signature_, repo_, git::repository_index(), and git::tree_lookup().
Referenced by get_commit(), and get_last_commit_message().
commit_initial()
void git::GitRepository::commit_initial () private
Make the first commit.
Function is called by init.
Note
slightly differs from commit because in this case, there is no previous commit to dock on.
References git::LibGitPointer< T >::get(), my_signature_, repo_, git::repository_index(), and git::tree_lookup().
Referenced by init().
get_commit() [1/3]
LibGitPointer< git_commit > git::GitRepository::get_commit () private
Get the HEAD commit.
Returns
C-type commit object
Referenced by commit(), get_commit(), and get_last_commit_message().
get_commit() [2/3]
LibGitPointer< git_commit > git::GitRepository::get_commit (const std::string & ref) private
Get a specific commit.
Parameters
ref Use Hex string identifier to find a commit
Returns
C-type commit object
References commit(), git::LibGitPointer< T >::get(), and repo_.
get_commit() [3/3]
LibGitPointer< git_commit > git::GitRepository::get_commit (int count) private
Get a specific commit.
Parameters
count Jump back NUMBER of commits behind HEAD
Returns
C-type commit object
References get_commit(), and task::to_string().
get_last_commit_message()
std::string git::GitRepository::get_last_commit_message ()
Return the commit message of the HEAD commit.
Returns
message of last commit (=HEAD)
References commit(), and get_commit().
get_path()
std::filesystem::path git::GitRepository::get_path () const
Returns member variable, which is the root dir of the git repository.
References repo_path_.
get_repo()
git_repository * git::GitRepository::get_repo ()
Returns a non-owning raw pointer to the current repository.
References git::LibGitPointer< T >::get(), and repo_.
init()
void git::GitRepository::init (const std::filesystem::path & file_path) private
Initialize a new git repository and commit all files in its path.
Note
This is a private member function because git repository init should be done by an LibGit Object Initialization
References commit_initial(), git::LibGitPointer< T >::get(), make_signature(), repo_, repo_path_, git::repository_init(), git::repository_open(), and update().
Referenced by GitRepository(), and reset_repo().
is_staged()
bool git::GitRepository::is_staged (FileStatus & filestats, const git_status_entry * s) static private
Check if the file from the status entry is not unstaged and collect the status in filestats.
Note
this function is solely called by collect_status. It has no other purpose.
Parameters
filestats a structure which will be filled with the status of the file if the file is staged
s status of the file. A struct which contains flags about every possible state
Returns
true if file is staged (and filestats initialized), else false
References git::FileStatus::changes, git::FileStatus::handling, and git::FileStatus::path_name.
Referenced by collect_status().
is_unstaged()
bool git::GitRepository::is_unstaged (FileStatus & filestats, const git_status_entry * s) static private
Check if the file from the status entry is not staged and collect the status in filestats.
Note
this function is solely called by collect_status. It has no other purpose.
Parameters
filestats a structure which will be filled with the status of the file if the file is unstaged
s status of the file. A struct which contains flags about every possible state
Returns
true if file is unstaged (and filestats initialized), else false
References git::FileStatus::changes, git::FileStatus::handling, and git::FileStatus::path_name.
Referenced by collect_status().
make_signature()
void git::GitRepository::make_signature () private
Load a git signature or create a default signature.
References git::LibGitPointer< T >::get(), my_signature_, repo_, git::signature_default(), and git::signature_new().
Referenced by init().
remove_directory()
void git::GitRepository::remove_directory (const std::filesystem::path & directory)
Deletes seq_repository and all files within.
Parameters
directory directory holding sequence
Attention
directory is a relative path within repo_path_
References git::LibGitPointer< T >::get(), repo_, repo_path_, and git::repository_index().
reset_repo()
void git::GitRepository::reset_repo ()
Reset all knowledge this object knows about the repository and load the knowledge again.
References init(), my_signature_, repo_, repo_path_, and git::LibGitPointer< T >::reset().
status()
std::vector< FileStatus > git::GitRepository::status ()
Returns current git status.
This includes unchanged, untracked and ingnored files and directories. Each files status is represented by – file name – change status (has the file changed) – handling status (what git will do with it)
Returns
vector of file status for each file.
References collect_status(), git::LibGitPointer< T >::get(), repo_, and git::status_list_new().
Referenced by collect_status().
update()
void git::GitRepository::update () private
Update the tracked files in the repository.
This member function stages all changes of already tracked files in the repository.
References git::LibGitPointer< T >::get(), repo_, and git::repository_index().
Referenced by init().
Member Data Documentation
my_signature_
LibGitPointer<git_signature> git::GitRepository::my_signature_ private
Signature used in commits.
Referenced by commit(), commit_initial(), make_signature(), reset_repo(), and ~GitRepository().
repo_
LibGitPointer<git_repository> git::GitRepository::repo_ private
Pointer which holds all infos of the active repository.
Referenced by add(), add_files(), commit(), commit_initial(), get_commit(), get_repo(), init(), make_signature(), remove_directory(), reset_repo(), status(), update(), and ~GitRepository().
repo_path_
std::filesystem::path git::GitRepository::repo_path_ private
Path to the repository.
Referenced by get_path(), GitRepository(), init(), remove_directory(), and reset_repo().
The documentation for this class was generated from the following files:
GitRepository.h
GitRepository.cc