Taskolib: task::Message Class Reference
task::Message Class Reference
Detailed Description
A message carrying some text, a timestamp, and a type, to be transported with a message queue between threads.
#include <Message.h>
Public Types
enum Type {
Type::output, Type::log_info, Type::log_warning, Type::log_error,
Type::sequence_started, Type::sequence_stopped, Type::sequence_stopped_with_error, Type::step_started,
Type::step_stopped, Type::step_stopped_with_error, Type::undefined
}
The type of this message.
using IndexType = std::uint16_t
Type for the associated index (for convenience, same as Sequence::SizeType)
Public Member Functions
Message ()=default
Construct an empty message.
Message (Type type, std::string text, TimePoint timestamp, IndexType index)
Construct an initialized message from the given parameters.
IndexType get_index () const noexcept
Return the associated index.
const std::string & get_text () const
Return the message text.
Type get_type () const noexcept
Return the message type.
TimePoint get_timestamp () const
Return the timestamp.
void set_index (IndexType index)
Set the associated index.
void set_text (const std::string &text)
Set the message text.
void set_timestamp (TimePoint timestamp)
Set the timestamp.
void set_type (Type type) noexcept
Set the message type.
Private Attributes
std::string text_
TimePoint timestamp_ {}
Type type_ { Type::output }
IndexType index_ { 0 }
Static Private Attributes
static constexpr std::array< char const *, static_cast< int >Type::undefined)+1 > type_description_
Friends
std::ostream & operator<< (std::ostream &stream, Type const &t)
std::ostream & operator<< (std::ostream &stream, Message const &mess)
Member Typedef Documentation
IndexType
using task::Message::IndexType = std::uint16_t
Type for the associated index (for convenience, same as Sequence::SizeType)
Member Enumeration Documentation
Type
enum task::Message::Type strong
The type of this message.
Enumerator
output
a message string that was output by a step via print()
log_info
a log entry of informational character
log_warning
a log entry carrying some kind of warning
log_error
a log entry carrying an error message
sequence_started
a sequence has been started
sequence_stopped
a sequence has stopped regularly
sequence_stopped_with_error
a sequence has been stopped because of an error
step_started
a step inside a sequence has been started
step_stopped
a step inside a sequence has stopped regularly
step_stopped_with_error
a step inside a sequence has been stopped because of an error
undefined
marker for last type
Constructor & Destructor Documentation
Message() [1/2]
task::Message::Message () default
Construct an empty message.
Message() [2/2]
task::Message::Message (Type type, std::string text, TimePoint timestamp, IndexType index) inline
Construct an initialized message from the given parameters.
Member Function Documentation
get_index()
IndexType task::Message::get_index () const inline noexcept
Return the associated index.
References index_.
Referenced by task::Executor::update().
get_text()
const std::string& task::Message::get_text () const inline
Return the message text.
This function returns a reference to a member variable. Be aware of the associated lifetime implications!
References text_.
Referenced by task::Executor::update().
get_timestamp()
TimePoint task::Message::get_timestamp () const inline
Return the timestamp.
References timestamp_.
Referenced by task::Executor::update().
get_type()
Type task::Message::get_type () const inline noexcept
Return the message type.
References type_.
Referenced by task::Executor::update().
set_index()
void task::Message::set_index (IndexType index) inline
Set the associated index.
References index_.
set_text()
void task::Message::set_text (const std::string & text) inline
Set the message text.
References text_.
set_timestamp()
void task::Message::set_timestamp (TimePoint timestamp) inline
Set the timestamp.
References timestamp_.
set_type()
void task::Message::set_type (Type type) inline noexcept
Set the message type.
References type_.
Friends And Related Function Documentation
operator<< [1/2]
std::ostream& operator<< (std::ostream & stream, Message const & mess) friend
operator<< [2/2]
std::ostream& operator<< (std::ostream & stream, Type const & t) friend
Member Data Documentation
index_
IndexType task::Message::index_ { 0 } private
Referenced by get_index(), and set_index().
text_
std::string task::Message::text_ private
Referenced by get_text(), and set_text().
timestamp_
TimePoint task::Message::timestamp_ {} private
Referenced by get_timestamp(), and set_timestamp().
type_
Type task::Message::type_ { Type::output } private
Referenced by get_type(), and set_type().
type_description_
constexpr std::array<char const*, static_cast<int>Type::undefined) + 1> task::Message::type_description_ static constexpr private
Initial value:
=
    {
        "output",
        "log_info",
        "log_warning",
        "log_error",
        "sequence_started",
        "sequence_stopped",
        "sequence_stopped_with_error",
        "step_started",
        "step_stopped",
        "step_stopped_with_error",
        "undefined"
    }
The documentation for this class was generated from the following file:
Message.h