Taskolib: git::LibGitPointer< T > Class Template Reference
git::LibGitPointer< T > Class Template Reference
Detailed Description
template<class T>
class git::LibGitPointer< T >
Template class wrapper for all libgit2 pointer types starting with git_{a-z}*.
Copy methods are excluded to prevent double ownership of said pointer.
Template Parameters
T A dereferencing from a pointer type like git_remote*, git_tree*, git_commit*, ...
#include <GitObjectWrapper.h>
Public Member Functions
LibGitPointer ()
(default) Default-construct an LibGitPointer. The managed pointer is NULL.
LibGitPointer (T *val)
(construct by value) Construct a LibGitPointer via a C-pointer from libgit2.
LibGitPointer (LibGitPointer &&lg)
(move constructor) Move a C-pointer from an existing LibGitPointer to a new one.
~LibGitPointer ()
(destructor) Destruct the Object by freeing the C-type pointer with a libgit function.
LibGitPointer & operator= (LibGitPointer &&lg) noexcept
(move assignment) move value from other object to this object.
LibGitPointer (const LibGitPointer &)=delete
(copy constructor) Shall not be used to prevent double ownership of pointer.
LibGitPointer & operator= (const LibGitPointer &)=delete
(copy assignment) Shall not be used to prevent double ownership of pointer.
void reset ()
Function to free member variables of GitRepository object before deconstruction of their owner.
T * get ()
Return a non-owning pointer to the managed object (or nullptr if no object is managed).
const T * get () const
Return a constant non-owning pointer to the managed object (or nullptr if no object is managed).
Private Attributes
T * val_ = nullptr
Constructor & Destructor Documentation
LibGitPointer() [1/4]
template<class T > git::LibGitPointer< T >::LibGitPointer () inline
(default) Default-construct an LibGitPointer. The managed pointer is NULL.
LibGitPointer() [2/4]
template<class T > git::LibGitPointer< T >::LibGitPointer (T * val) inline
(construct by value) Construct a LibGitPointer via a C-pointer from libgit2.
LibGitPointer() [3/4]
template<class T > git::LibGitPointer< T >::LibGitPointer (LibGitPointer< T > && lg) inline
(move constructor) Move a C-pointer from an existing LibGitPointer to a new one.
~LibGitPointer()
template<class T > git::LibGitPointer< T >::~LibGitPointer () inline
(destructor) Destruct the Object by freeing the C-type pointer with a libgit function.
References git::free_libgit_ptr(), and git::LibGitPointer< T >::val_.
LibGitPointer() [4/4]
template<class T > git::LibGitPointer< T >::LibGitPointer (const LibGitPointer< T > &) delete
(copy constructor) Shall not be used to prevent double ownership of pointer.
Member Function Documentation
get() [1/2]
template<class T > T* git::LibGitPointer< T >::get () inline
Return a non-owning pointer to the managed object (or nullptr if no object is managed).
References git::LibGitPointer< T >::val_.
Referenced by git::GitRepository::add(), git::GitRepository::add_files(), git::GitRepository::commit(), git::GitRepository::commit_initial(), git::GitRepository::get_commit(), git::GitRepository::get_repo(), git::GitRepository::init(), git::GitRepository::make_signature(), git::GitRepository::remove_directory(), git::GitRepository::status(), and git::GitRepository::update().
get() [2/2]
template<class T > const T* git::LibGitPointer< T >::get () const inline
Return a constant non-owning pointer to the managed object (or nullptr if no object is managed).
References git::LibGitPointer< T >::val_.
operator=() [1/2]
template<class T > LibGitPointer& git::LibGitPointer< T >::operator= (const LibGitPointer< T > &) delete
(copy assignment) Shall not be used to prevent double ownership of pointer.
operator=() [2/2]
template<class T > LibGitPointer& git::LibGitPointer< T >::operator= (LibGitPointer< T > && lg) inline noexcept
(move assignment) move value from other object to this object.
References git::LibGitPointer< T >::val_.
reset()
template<class T > void git::LibGitPointer< T >::reset () inline
Function to free member variables of GitRepository object before deconstruction of their owner.
necessary because they have to be freed before the libgit2 environment deconstruction, see: git_libgit2_shutdown()
References git::free_libgit_ptr(), and git::LibGitPointer< T >::val_.
Referenced by git::GitRepository::reset_repo(), and git::GitRepository::~GitRepository().
Member Data Documentation
val_
template<class T > T* git::LibGitPointer< T >::val_ = nullptr private
Referenced by git::LibGitPointer< T >::get(), git::LibGitPointer< T >::operator=(), git::LibGitPointer< T >::reset(), and git::LibGitPointer< T >::~LibGitPointer().
The documentation for this class was generated from the following file:
GitObjectWrapper.h